version: '2'
services:
  ogp-solr:
    image: solr
    container_name: ogp-solr
    ports:
     - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
  db:
    image: mysql
    command: --max_allowed_packet=100M
    ports:
      - "3306"
    volumes:
      - "$HOME/tmp/ogp/mysql:/var/lib/mysql"
      - "./mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
    environment:
      - MYSQL_DATABASE=ogp
      - MYSQL_ROOT_PASSWORD=root
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "8010:80"
    environment:
      - MYSQL_PORT_3306_TCP_ADDR=db
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_USER=root
      - MYSQL_DATABASE=ogp
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    container_name: ogp
    volumes:
      - "./:/var/www/html"
      - "./docker/web/php.ini:/etc/php5/cli/php.ini"
    links:
      - db
      - ogp-solr
volumes:
  data: