<?php
/**
 * @file
 * ogp_working_groups.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function ogp_working_groups_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "context" && $api == "context") {
    return array("version" => "3");
  }
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function ogp_working_groups_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_node_info().
 */
function ogp_working_groups_node_info() {
  $items = array(
    'working_group' => array(
      'name' => t('Working Group'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Name'),
      'help' => '',
    ),
    'working_group_page' => array(
      'name' => t('Working Group Page'),
      'base' => 'node_content',
      'description' => t('Just like a regular "page" node, but belongs to a particular working group.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
