<?php
/**
 * @file
 * test_default.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function test_default_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['bean-americas-regional-meeting'] = array(
    'cache' => 1,
    'css_class' => 'meeting-block-title-image',
    'custom' => 0,
    'delta' => 'americas-regional-meeting',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 1,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-explorer-landing'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'explorer-landing',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 26,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-front-slideshow'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'front-slideshow',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 52,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-home-page-mexico-summit-promotio'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'home-page-mexico-summit-promotio',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 63,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-london-2013'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'london-2013',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 73,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-london-2013-header-block'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'london-2013-header-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 74,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-network-blogrollw'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'network-blogrollw',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 82,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-non-ogp-slideshow'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'non-ogp-slideshow',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 188,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-priority-links---awards'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'priority-links---awards',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 91,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-priority-links---awards-regional'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'priority-links---awards-regional',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 92,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-priority-links---news--events'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'priority-links---news--events',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 93,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-priority-links-for-home-page-dur'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'priority-links-for-home-page-dur',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 94,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-splash-header'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'splash-header',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 106,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-splash-header---awards'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'splash-header---awards',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 107,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-splash-header---news'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'splash-header---news',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 108,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-tools---develop-your-action-plan'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'tools---develop-your-action-plan',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 125,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-tools---irm'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'tools---irm',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 126,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-tools---learn-from-your-peers'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'tools---learn-from-your-peers',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 127,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-tools---track-progress-on-ogp'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'tools---track-progress-on-ogp',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 128,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['block-copyright_text'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'machine_name' => 'copyright_text',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 7,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['block-demo'] = array(
    'cache' => -1,
    'css_class' => 'demo',
    'custom' => 0,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'machine_name' => 'demo',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '<front>',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 15,
      ),
    ),
    'title' => 'Demo',
    'visibility' => 1,
  );

  $export['block-empowered'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'machine_name' => 'empowered',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 23,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['block-explorer_landing_text'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'machine_name' => 'explorer_landing_text',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 27,
      ),
    ),
    'title' => 'Easy Access to the Wealth of OGP Data',
    'visibility' => 0,
  );

  $export['block-flickr'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'machine_name' => 'flickr',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 43,
      ),
    ),
    'title' => 'Flickr Stream',
    'visibility' => 0,
  );

  $export['block-front_accountability'] = array(
    'cache' => -1,
    'css_class' => 'front-accountability',
    'custom' => 0,
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'machine_name' => 'front_accountability',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 53,
      ),
    ),
    'title' => 'Accountability',
    'visibility' => 0,
  );

  $export['block-front_innovation'] = array(
    'cache' => -1,
    'css_class' => 'front-innovation',
    'custom' => 0,
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'machine_name' => 'front_innovation',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 54,
      ),
    ),
    'title' => 'Technology & Innovation',
    'visibility' => 0,
  );

  $export['block-front_participation'] = array(
    'cache' => -1,
    'css_class' => 'front-participation',
    'custom' => 0,
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'machine_name' => 'front_participation',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 56,
      ),
    ),
    'title' => 'Citizen Participation',
    'visibility' => 0,
  );

  $export['block-front_transparency'] = array(
    'cache' => -1,
    'css_class' => 'front-transparency',
    'custom' => 0,
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'machine_name' => 'front_transparency',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 57,
      ),
    ),
    'title' => 'Transparency',
    'visibility' => 0,
  );

  $export['block-front_video'] = array(
    'cache' => -1,
    'css_class' => 'front-video',
    'custom' => 0,
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'machine_name' => 'front_video',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 58,
      ),
    ),
    'title' => 'Open Government Partnership Global Summit Livestream',
    'visibility' => 0,
  );

  $export['block-front_video_asia'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'machine_name' => 'front_video_asia',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 60,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['block-front_video_europe'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'machine_name' => 'front_video_europe',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 61,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['block-latest_event_link'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'machine_name' => 'latest_event_link',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 83,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['block-logo_opg_header'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'machine_name' => 'logo_opg_header',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => 'topbar',
        'status' => 1,
        'theme' => 'ogp_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['block-map_home_page'] = array(
    'cache' => -1,
    'css_class' => 'map-home-page',
    'custom' => 0,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'machine_name' => 'map_home_page',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '<front>',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 78,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['comment-recent'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'recent',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'comment',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 96,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['context_ui-editor'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'editor',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'context_ui',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 6,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['diff-inline'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'inline',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'diff',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 67,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['disqus-disqus_combination_widget'] = array(
    'cache' => 8,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'disqus_combination_widget',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'disqus',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 17,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['disqus-disqus_comments'] = array(
    'cache' => -2,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'disqus_comments',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'disqus',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 18,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['disqus-disqus_popular_threads'] = array(
    'cache' => 8,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'disqus_popular_threads',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'disqus',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 19,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['disqus-disqus_recent_comments'] = array(
    'cache' => 8,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'disqus_recent_comments',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'disqus',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 20,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['disqus-disqus_top_commenters'] = array(
    'cache' => 8,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'disqus_top_commenters',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'disqus',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 21,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['dkan_dataset-dkan_dataset_dataset_help'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'dkan_dataset_dataset_help',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'dkan_dataset',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 181,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['dkan_dataset-dkan_dataset_resource_help'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'dkan_dataset_resource_help',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'dkan_dataset',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 182,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['dkan_dataset-dkan_dataset_resource_nodes'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'dkan_dataset_resource_nodes',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'dkan_dataset',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 98,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['easy_breadcrumb-easy_breadcrumb'] = array(
    'cache' => 4,
    'css_class' => 'c-bread-crumb',
    'custom' => 0,
    'delta' => 'easy_breadcrumb',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'easy_breadcrumb',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 22,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-u4aNc9BVPgvuxegraAOFIU30dlNr6xQy'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'u4aNc9BVPgvuxegraAOFIU30dlNr6xQy',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 36,
      ),
    ),
    'title' => 'Author',
    'visibility' => 0,
  );

  $export['lang_dropdown-language'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'language',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'lang_dropdown',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 71,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['lang_dropdown-language_content'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'language_content',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'lang_dropdown',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 70,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['locale-language_content'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'language_content',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'locale',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 68,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu-devel'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'devel',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 16,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu-menu-footer-menu'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'menu-footer-menu',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 50,
      ),
    ),
    'title' => 'OGP',
    'visibility' => 0,
  );

  $export['menu-menu-menu-navigation'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'menu-menu-navigation',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 79,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu-menu-menu-ogp'] = array(
    'cache' => -1,
    'css_class' => 'm-menu',
    'custom' => 0,
    'delta' => 'menu-menu-ogp',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 187,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu-menu-menu-quick-links'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'menu-menu-quick-links',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 95,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu-menu-menuogp'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'menu-menuogp',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 80,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu-menu-og-285'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'menu-og-285',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu-menu-og-293'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'menu-og-293',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu-menu-og-3698'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'menu-og-3698',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu-menu-og-5486'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'menu-og-5486',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu-menu-og-5717'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'menu-og-5717',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu-menu-og-5758'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'menu-og-5758',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu-menu-og-5889'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'menu-og-5889',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu-menu-og-6622'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'menu-og-6622',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu-menu-og-8424'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'menu-og-8424',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu-menu-og-9232'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'menu-og-9232',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu_block-1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 1,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 75,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['menu_block-10'] = array(
    'cache' => -1,
    'css_class' => 'meeting-block-menu',
    'custom' => 0,
    'delta' => 10,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 25,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['menu_block-12'] = array(
    'cache' => -1,
    'css_class' => 'c-menu -white',
    'custom' => 0,
    'delta' => 12,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '<front>',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => 'topbar',
        'status' => 1,
        'theme' => 'ogp_theme',
        'weight' => 2,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['menu_block-13'] = array(
    'cache' => -1,
    'css_class' => 'c-menu',
    'custom' => 0,
    'delta' => 13,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '<front>',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => 'topbar',
        'status' => 1,
        'theme' => 'ogp_theme',
        'weight' => 1,
      ),
    ),
    'title' => 'menuogp',
    'visibility' => 0,
  );

  $export['menu_block-2'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 2,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 51,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['menu_block-3'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 3,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 48,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu_block-4'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 4,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 44,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu_block-5'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 5,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 47,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu_block-6'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 6,
    'i18n_block_language' => array(
      0 => 'es',
    ),
    'i18n_mode' => 0,
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 46,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu_block-7'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 7,
    'i18n_block_language' => array(
      0 => 'es',
    ),
    'i18n_mode' => 0,
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 45,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu_block-8'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 8,
    'i18n_block_language' => array(
      0 => 'es',
    ),
    'i18n_mode' => 0,
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 49,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu_block-9'] = array(
    'cache' => -1,
    'css_class' => 'meeting-block-menu',
    'custom' => 0,
    'delta' => 9,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['menu_block-ogp_blog-1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ogp_blog-1',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 101,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu_block-ogp_page-1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ogp_page-1',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 100,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['multiblock-2'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 2,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'multiblock',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => 'contentCountries',
        'status' => 1,
        'theme' => 'ogp_theme',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['multiblock-3'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 3,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'multiblock',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => 'contentStories',
        'status' => 1,
        'theme' => 'ogp_theme',
        'weight' => 1,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['node-recent'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'recent',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'node',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 97,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['node-syndicate'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'syndicate',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'node',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 113,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['og_extras-group_info'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'group_info',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'og_extras',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 62,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['og_extras-node_links'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'node_links',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'og_extras',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 84,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['og_menu-og_multi_menu_block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'og_multi_menu_block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'og_menu',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 85,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['og_menu-og_single_menu_block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'og_single_menu_block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'og_menu',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 86,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['ogp_activity_stream-ogp_rss'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ogp_rss',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'ogp_activity_stream',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 89,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['ogp_country-nav'] = array(
    'cache' => -1,
    'css_class' => 'meeting-block-menu',
    'custom' => 0,
    'delta' => 'nav',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'ogp_country',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 11,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['ogp_country-overview'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'overview',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'ogp_country',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 12,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['ogp_dkan_integration-action_plan_table'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'action_plan_table',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'ogp_dkan_integration',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 9,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['ogp_dkan_integration-case_study_table'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'case_study_table',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'ogp_dkan_integration',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 10,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['ogp_dkan_integration-irm_report_table'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'irm_report_table',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'ogp_dkan_integration',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 13,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['ogp_dkan_integration-irm_reports_by_country'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'irm_reports_by_country',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'ogp_dkan_integration',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 65,
      ),
    ),
    'title' => 'Most Recent IRM Reports: Download or Comment',
    'visibility' => 0,
  );

  $export['ogp_dkan_integration-self_assessment_table'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'self_assessment_table',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'ogp_dkan_integration',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 14,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['ogp_map-country_apc'] = array(
    'cache' => 1,
    'css_class' => 'c-map-apc',
    'custom' => 0,
    'delta' => 'country_apc',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'ogp_map',
    'node_types' => array(),
    'pages' => '<front>',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'ogp_theme',
        'weight' => 3,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['ogp_map-country_map'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'country_map',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'ogp_map',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 87,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['ogp_map-country_sc'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'country_sc',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'ogp_map',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 88,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['ogp_topics-ogp_topics_hint1'] = array(
    'cache' => 8,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ogp_topics_hint1',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'ogp_topics',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 191,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['ogp_topics-ogp_topics_hint2'] = array(
    'cache' => 8,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ogp_topics_hint2',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'ogp_topics',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 189,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['search-form'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'form',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'search',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 99,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['sharethis-sharethis_block'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'sharethis_block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'sharethis',
    'node_types' => array(),
    'pages' => '<front>
independent-reporting-mechanism
countries
node/6636
node/6638',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 102,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['shortcut-shortcuts'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'shortcuts',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'shortcut',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 103,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['superfish-1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 1,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'superfish',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 109,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['superfish-2'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 2,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'superfish',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 110,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['superfish-3'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 3,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'superfish',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 111,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['superfish-4'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 4,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'superfish',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 112,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['system-help'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'help',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'system',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 114,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['system-main'] = array(
    'cache' => -1,
    'css_class' => 'hidden-facebook',
    'custom' => 0,
    'delta' => 'main',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'system',
    'node_types' => array(),
    'pages' => '<front>',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'ogp_theme',
        'weight' => 1,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['system-main-menu'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'main-menu',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'system',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 76,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['system-management'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'management',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'system',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 77,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['system-navigation'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'navigation',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'system',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 81,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['system-powered-by'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'powered-by',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'system',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 90,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['system-user-menu'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'user-menu',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'system',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 131,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['tagclouds-11'] = array(
    'cache' => 8,
    'css_class' => '',
    'custom' => 0,
    'delta' => 11,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'tagclouds',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 119,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['tagclouds-12'] = array(
    'cache' => 8,
    'css_class' => '',
    'custom' => 0,
    'delta' => 12,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'tagclouds',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 121,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['tagclouds-13'] = array(
    'cache' => 8,
    'css_class' => '',
    'custom' => 0,
    'delta' => 13,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'tagclouds',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 120,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['tagclouds-4'] = array(
    'cache' => 8,
    'css_class' => '',
    'custom' => 0,
    'delta' => 4,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'tagclouds',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 116,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['tagclouds-5'] = array(
    'cache' => 8,
    'css_class' => '',
    'custom' => 0,
    'delta' => 5,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'tagclouds',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 124,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['tagclouds-6'] = array(
    'cache' => 8,
    'css_class' => '',
    'custom' => 0,
    'delta' => 6,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'tagclouds',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 115,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['tagclouds-7'] = array(
    'cache' => 8,
    'css_class' => '',
    'custom' => 0,
    'delta' => 7,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'tagclouds',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 117,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['tagclouds-8'] = array(
    'cache' => 8,
    'css_class' => '',
    'custom' => 0,
    'delta' => 8,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'tagclouds',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 122,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['tagclouds-9'] = array(
    'cache' => 8,
    'css_class' => '',
    'custom' => 0,
    'delta' => 9,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'tagclouds',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 118,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['user-login'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'login',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'user',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 130,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['user-new'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'new',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'user',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 183,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['user-online'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'online',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'user',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 184,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views--exp-ogp_search-page'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '-exp-ogp_search-page',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 28,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views--exp-ogp_search-search_block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '-exp-ogp_search-search_block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 29,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views--exp-ogp_topics-page'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '-exp-ogp_topics-page',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 1,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-0c42da2d7e7c4a0583d7210d92a53820'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '0c42da2d7e7c4a0583d7210d92a53820',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 166,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-0fae63945e02e382981f761866b34c14'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '0fae63945e02e382981f761866b34c14',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 135,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-1452c1f5fc78c14899eb269a60112951'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '1452c1f5fc78c14899eb269a60112951',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 136,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-2020b6faf318d675a2d569cadb0edf62'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '2020b6faf318d675a2d569cadb0edf62',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 132,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-39b0a4186ac439edb3e86a0a3e7c6f5a'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '39b0a4186ac439edb3e86a0a3e7c6f5a',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 164,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-53321caaa35ce92e009116d15d119263'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '53321caaa35ce92e009116d15d119263',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 134,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-5cf30a536448365f9fab7ebcb5da5ddf'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '5cf30a536448365f9fab7ebcb5da5ddf',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 168,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-619945e9144b15c5a8eb99974151fa28'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '619945e9144b15c5a8eb99974151fa28',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 167,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-9cf22433e0efbd8b206c8e4c2edb177c'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '9cf22433e0efbd8b206c8e4c2edb177c',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 177,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-ba8e2990f22a2185eec71f6c9d77beac'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ba8e2990f22a2185eec71f6c9d77beac',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 140,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-be9020110c2b80337a6d8b3fbfda8e1c'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'be9020110c2b80337a6d8b3fbfda8e1c',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 169,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-blog_authors-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'blog_authors-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 141,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-blog_categories-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'blog_categories-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 133,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-blog_category_achive-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'blog_category_achive-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 4,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-blog_category_term-block_1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'blog_category_term-block_1',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 138,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-bloggers_posts-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'bloggers_posts-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 142,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-bloggrid-block'] = array(
    'cache' => -1,
    'css_class' => 'blog-grid',
    'custom' => 0,
    'delta' => 'bloggrid-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => 'contentStories',
        'status' => 1,
        'theme' => 'ogp_theme',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['views-c67ac7f11821ca8044211a8daf1e9807'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'c67ac7f11821ca8044211a8daf1e9807',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 145,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-cc103d070c5696fe7c7ea448fef740e6'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'cc103d070c5696fe7c7ea448fef740e6',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 165,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-country_blog_content-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'country_blog_content-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 144,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-country_header-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'country_header-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 147,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-country_links-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'country_links-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 148,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-cover_home_page-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'cover_home_page-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '<front>',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 149,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['views-cse_subscribe_block-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'cse_subscribe_block-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 143,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-demo-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'demo-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 150,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-e127ea55e2aa984ec7be21ea009922fc'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'e127ea55e2aa984ec7be21ea009922fc',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 137,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-ed59f78fd166517b4d8bc8bb21b3189d'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ed59f78fd166517b4d8bc8bb21b3189d',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 139,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-ef62ad50c9cf51f742d6778835e0782e'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ef62ad50c9cf51f742d6778835e0782e',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 146,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-irm_reports_legacy-block_1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'irm_reports_legacy-block_1',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 151,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-irm_reports_legacy-block_2'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'irm_reports_legacy-block_2',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 152,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-irm_text_latvia-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'irm_text_latvia-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 153,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-news-news_block_1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'news-news_block_1',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 72,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-og_extras_members-block_1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'og_extras_members-block_1',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 154,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-og_members-block_1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'og_members-block_1',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 155,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-ogp_activity_feed-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ogp_activity_feed-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 156,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-ogp_activity_feed-block_1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ogp_activity_feed-block_1',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 158,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-ogp_activity_feed-block_2'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ogp_activity_feed-block_2',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 159,
      ),
    ),
    'title' => 'Activity Stream',
    'visibility' => 0,
  );

  $export['views-ogp_activity_feed-block_3'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ogp_activity_feed-block_3',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 157,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-ogp_activity_feed-block_4'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ogp_activity_feed-block_4',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 160,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-ogp_blog-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ogp_blog-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 104,
      ),
    ),
    'title' => 'Latest Blog Posts',
    'visibility' => 0,
  );

  $export['views-ogp_commitments-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ogp_commitments-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 161,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-ogp_country_overview-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ogp_country_overview-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 162,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-ogp_country_staff-block_1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ogp_country_staff-block_1',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 163,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-ogp_map_countries-block_1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ogp_map_countries-block_1',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 171,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-ogp_map_countries-block_2'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ogp_map_countries-block_2',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 170,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-ogp_news_and_events_blog-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ogp_news_and_events_blog-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 105,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-related_content-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'related_content-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 172,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-short_user_info-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'short_user_info-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 173,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-slider_cover_home_page-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'slider_cover_home_page-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '<front>',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'ogp_theme',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['views-slidersecondary-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'slidersecondary-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 178,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-slideshow-block_1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'slideshow-block_1',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 180,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-slideshow-block_2'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'slideshow-block_2',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 179,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-summit_tagged_posts-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'summit_tagged_posts-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 174,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-tweets-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'tweets-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 129,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-workbench_current_user-block_1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'workbench_current_user-block_1',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 175,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-workbench_edited-block_1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'workbench_edited-block_1',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 176,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['workbench-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'workbench',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ogp_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ogp_theme',
        'weight' => 185,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
