<?php
/**
 * @file
 * ogp_dkan_integration.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function ogp_dkan_integration_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-5K6xUsVIKUpfAyC0LKSF7mLSXqXsZgqI'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '5K6xUsVIKUpfAyC0LKSF7mLSXqXsZgqI',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'at_ogp' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'at_ogp',
        'weight' => 0,
      ),
    ),
    'title' => 'Topics',
    'visibility' => 0,
  );

  $export['facetapi-MZ5wcE5ZJ8p3n2mJZ0H5iw48vxzuSewu'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'MZ5wcE5ZJ8p3n2mJZ0H5iw48vxzuSewu',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'at_ogp' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'at_ogp',
        'weight' => 0,
      ),
    ),
    'title' => 'Document Type',
    'visibility' => 0,
  );

  $export['facetapi-TdXDIQZjr0sqAOQon3npKpyf1qVLuDGs'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'TdXDIQZjr0sqAOQon3npKpyf1qVLuDGs',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'at_ogp' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'at_ogp',
        'weight' => 0,
      ),
    ),
    'title' => 'Format',
    'visibility' => 0,
  );

  $export['facetapi-n02iwD1VPpAhtjjaaSWjYmVk2PUA0YZj'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'n02iwD1VPpAhtjjaaSWjYmVk2PUA0YZj',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'at_ogp' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'at_ogp',
        'weight' => 0,
      ),
    ),
    'title' => 'Event Type',
    'visibility' => 0,
  );

  $export['facetapi-szP2NgXCNkPbnejF6vGJMf0gln6BiCtu'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'szP2NgXCNkPbnejF6vGJMf0gln6BiCtu',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'at_ogp' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'at_ogp',
        'weight' => 0,
      ),
    ),
    'title' => 'Country',
    'visibility' => 0,
  );

  $export['facetapi-tWo2FGhrJSXp1sLmNfh8OQ5oSSjke0sa'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'tWo2FGhrJSXp1sLmNfh8OQ5oSSjke0sa',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'at_ogp' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'at_ogp',
        'weight' => 0,
      ),
    ),
    'title' => 'Resource Type',
    'visibility' => 0,
  );

  return $export;
}
